# -*- coding: utf-8 -*-
"""Generate a .def file that re-exports every export of a system DLL as a
forwarder to the System32 copy, so a proxy DLL with the same file name behaves
exactly like the real one for every caller in the process.

usage: py -3 gen_proxy_def.py [--system32 <dir>] [name ...]

Writes def/<name>.def next to this script (one directory up) and prints what it
found. Functions exported only by ordinal cannot be forwarded by name; they are
reported and skipped.

read_exports() is also used by tools/run_tests.py to compare a built proxy
against the system DLL it replaces.
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEF_DIR = os.path.join(os.path.dirname(HERE), 'def')


def read_exports(path):
    """Return (entries, ordinal_only). Each entry is a dict with 'name',
    'ordinal' and 'forwarder' (the string this export forwards to, or None when
    the export is real code)."""
    data = open(path, 'rb').read()
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    assert data[pe:pe+4] == b'PE\0\0', path
    fh = pe + 4
    nsec, = struct.unpack_from('<H', data, fh + 2)
    optsz, = struct.unpack_from('<H', data, fh + 16)
    opt = fh + 20
    magic, = struct.unpack_from('<H', data, opt)
    is64 = magic == 0x20b
    dd = opt + (112 if is64 else 96)
    exp_rva, exp_size = struct.unpack_from('<II', data, dd)
    so = opt + optsz
    secs = []
    for i in range(nsec):
        vsz, va, rsz, ro = struct.unpack_from('<IIII', data, so + 40 * i + 8)
        secs.append((va, max(vsz, rsz), ro))

    def r2o(rva):
        for va, vsz, ro in secs:
            if va <= rva < va + vsz:
                return ro + (rva - va)
        return None

    def cstr(off):
        end = data.find(b'\0', off)
        return data[off:end].decode('latin1')

    def section_of(rva):
        for va, vsz, ro in secs:
            if va <= rva < va + vsz:
                return va
        return None

    exp_section = section_of(exp_rva)

    def forwarder_of(rva):
        # A forwarder is an export whose RVA points into the export data itself
        # (the same section as the export directory) rather than into code.
        if section_of(rva) != exp_section:
            return None
        text = cstr(r2o(rva))
        if not text or '.' not in text or any(ord(c) < 32 or ord(c) > 126 for c in text):
            return None
        return text

    base, = struct.unpack_from('<I', data, r2o(exp_rva) + 16)
    nfunc, nname = struct.unpack_from('<II', data, r2o(exp_rva) + 20)
    aof, anof, aord = struct.unpack_from('<III', data, r2o(exp_rva) + 28)

    named = {}
    for i in range(nname):
        name_rva, = struct.unpack_from('<I', data, r2o(anof) + 4 * i)
        index, = struct.unpack_from('<H', data, r2o(aord) + 2 * i)
        named[index] = cstr(r2o(name_rva))

    entries = []
    ordinal_only = 0
    for i in range(nfunc):
        func_rva, = struct.unpack_from('<I', data, r2o(aof) + 4 * i)
        if func_rva == 0:
            continue
        forwarder = forwarder_of(func_rva)
        if i in named:
            entries.append({'name': named[i], 'ordinal': i + base, 'forwarder': forwarder})
        else:
            ordinal_only += 1
    return entries, ordinal_only


def main():
    args = sys.argv[1:]
    sys32 = r'C:\Windows\System32'
    if '--system32' in args:
        i = args.index('--system32')
        sys32 = args[i + 1]
        del args[i:i + 2]
    names = args or ['dxgi', 'winmm', 'version', 'd3d11', 'd3dcompiler_47']

    os.makedirs(DEF_DIR, exist_ok=True)
    for name in names:
        dll = name if name.lower().endswith('.dll') else name + '.dll'
        path = os.path.join(sys32, dll)
        exports, ordinal_only = read_exports(path)
        # The forwarder target uses forward slashes: GNU ld's .def lexer treats
        # '\' as an escape, and the loader accepts either separator.
        target_dll = (sys32.rstrip('\\/') + '/' + dll).replace('\\', '/')
        lines = ['; %s -- proxy export list, generated by tools/gen_proxy_def.py' % dll,
                 '; every name is forwarded to the real DLL in System32.',
                 '; %d named export(s)' % len(exports)]
        if ordinal_only:
            lines.append('; WARNING: %d export(s) are ordinal-only and are NOT forwarded'
                         % ordinal_only)
        lines.append('LIBRARY %s' % dll)
        lines.append('EXPORTS')
        for entry in exports:
            lines.append('  %s = %s.%s @ %d'
                         % (entry['name'], target_dll, entry['name'], entry['ordinal']))
        out = os.path.join(DEF_DIR, name.split('.')[0] + '.def')
        with open(out, 'w', encoding='ascii', newline='\r\n') as fh:
            fh.write('\n'.join(lines) + '\n')
        print('%-14s %4d named exports, %d ordinal-only  ->  %s'
              % (dll, len(exports), ordinal_only, out))


if __name__ == '__main__':
    main()
